### PR TITLE
Navigation Kit docs

### PR DESCRIPTION
**Pull request by davidgyoung**
This is a work in progress.  Starting to build out the documentation for Navigation Kit.

### CODE REVIEW

**Comment by davidgyoung** [comment]
I have added an Android how to page for setting up the aar file, NavigationKit.plist, maps, and instantiating a MapView.

**Comment by syoder** [comment]
There is now an iOS how-to page as well as the SDK appledocs.  Do we want to merge this or is there more to do?

**Comment by davidgyoung** [comment]
I know Matt wants ro update the Android ref app and the SDK to fix a < SDK 18 issue.  

But we could probably merge first.  I doubt lots of people will stumble across this -- it is not linked from our site!  But by making it public we can share with the Verizon Center app developers.

**Comment by syoder** [comment]
We can wait, but I think once this is merged we will have everything we need to send out.

**Comment by davidgyoung** [comment]
Let's merge and try to get Francis, James or Matt to try the setup instructions.  Good to validate before sending out!

**Pull request merged**
